#!/usr/bin/env bash
#
# Package and sideload the Roku app onto a Roku in Developer Mode.
#
#   ./deploy.sh                 # uses ROKU_IP / ROKU_DEV_PASSWORD from env or .env
#   ROKU_IP=192.168.1.50 ./deploy.sh
#   ./deploy.sh --package-only  # just build roku-app.zip, don't upload
#
set -euo pipefail

cd "$(dirname "$0")"

# Optional: read deployment settings from roku/.env (gitignored). .env is
# meant to provide *defaults* - an explicit inline override (e.g.
# `ROKU_IP=... ./deploy.sh`, as documented above) must win over it, so
# preserve anything already set in the environment before sourcing.
if [[ -f .env ]]; then
  _prior_roku_ip="${ROKU_IP:-}"
  _prior_roku_password="${ROKU_DEV_PASSWORD:-}"
  _prior_web_url="${HDHOMERUN_WEB_URL:-}"
  # shellcheck disable=SC1091
  source .env
  [[ -n "$_prior_roku_ip" ]] && ROKU_IP="$_prior_roku_ip"
  [[ -n "$_prior_roku_password" ]] && ROKU_DEV_PASSWORD="$_prior_roku_password"
  [[ -n "$_prior_web_url" ]] && HDHOMERUN_WEB_URL="$_prior_web_url"
fi

ZIP_NAME="roku-app.zip"
BUILD_DIR=".roku-package"
PACKAGE_ONLY=0
[[ "${1:-}" == "--package-only" ]] && PACKAGE_ONLY=1

# --- build the package ------------------------------------------------------
# The manifest MUST sit at the zip root - zipping the parent folder is the
# single most common reason a sideload is rejected.
rm -f "$ZIP_NAME"
rm -rf -- "$BUILD_DIR"
trap 'rm -rf -- ".roku-package"' EXIT

mkdir "$BUILD_DIR"
cp -R manifest source components images "$BUILD_DIR"/

if [[ -n "${HDHOMERUN_WEB_URL:-}" ]]; then
  if [[ ! "$HDHOMERUN_WEB_URL" =~ ^https?://[^[:space:]\"\']+$ ]]; then
    echo "ERROR: HDHOMERUN_WEB_URL must be an http:// or https:// URL without spaces or quotes." >&2
    exit 1
  fi

  server_url="${HDHOMERUN_WEB_URL%/}"
  cat > "$BUILD_DIR/components/DeployConfig.brs" <<EOF
' Generated by deploy.sh from HDHOMERUN_WEB_URL.
function GetPackagedServerUrl() as string
    return "$server_url"
end function
EOF
fi

(
  cd "$BUILD_DIR"
  zip -r -q "../$ZIP_NAME" manifest source components images \
    -x '*.DS_Store' -x '*/.*'
)

echo "Built $ZIP_NAME ($(du -h "$ZIP_NAME" | cut -f1))"

if [[ -f "$ZIP_NAME" ]]; then
  if ! unzip -l "$ZIP_NAME" | grep -qE '^\s+[0-9]+.*\smanifest$'; then
    echo "ERROR: manifest is not at the zip root - Roku will reject this." >&2
    exit 1
  fi
fi

[[ $PACKAGE_ONLY -eq 1 ]] && exit 0

# --- upload -----------------------------------------------------------------
: "${ROKU_IP:?Set ROKU_IP (e.g. export ROKU_IP=192.168.1.50) or put it in roku/.env}"
: "${ROKU_DEV_PASSWORD:?Set ROKU_DEV_PASSWORD (the Developer Mode password) or put it in roku/.env}"

echo "Uploading to http://$ROKU_IP ..."

response=$(curl -sS --fail-with-body --digest \
  -u "rokudev:$ROKU_DEV_PASSWORD" \
  -F "mysubmit=Install" \
  -F "archive=@$ZIP_NAME" \
  -F "passwd=" \
  "http://$ROKU_IP/plugin_install" 2>&1) || {
    echo "Upload failed. Check that:" >&2
    echo "  - the Roku at $ROKU_IP is in Developer Mode" >&2
    echo "  - ROKU_DEV_PASSWORD matches the password you set (not your Roku account password)" >&2
    echo "$response" >&2
    exit 1
  }

# Roku returns an HTML page; pull out the status line it embeds.
if grep -qi "Identical to previous version" <<<"$response"; then
  echo "Roku reports this build is identical to the installed one."
  echo "Bump build_version in roku/manifest to force a reinstall."
elif grep -qi "success\|received\|installed" <<<"$response"; then
  echo "Installed. Launch it from the Roku home screen."
else
  echo "Upload completed but the response was unexpected:" >&2
  sed -e 's/<[^>]*>//g' <<<"$response" | grep -v '^\s*$' | head -20 >&2
fi

echo
echo "Debug console:  telnet $ROKU_IP 8085"
